version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: webiti
    restart: always
    environment:
      POSTGRES_DB: webitidb
      POSTGRES_USER: webiti
      POSTGRES_PASSWORD: webiti
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
